# Comparison Operators

In [2]:
import numpy as np
np_length = np.array([2.7, 3.4, 4.7, 6.6, 7.8])
np_breath = np.array([3.7, 1.4, 2.7, 3.6, 1.8])
np_height = np.array([1.7, 2.4, 1.7, 0.6, 1.8])
vol_cuboid = np_length * np_breath * np_height
vol_cuboid

array([16.983, 11.424, 21.573, 14.256, 25.272])

Q1. Show the vol_cuboid which are greater than 15 (2 marks)

In [52]:
## Start code here
vol_cuboid_grt_15=vol_cuboid[vol_cuboid>15]
vol_cuboid_grt_15
## End here

array([16.983, 21.573, 25.272])

## Numeric & Variable Comparison

Using comparison operators show:

Q1. If 10.5 is greater thean 10 (1 mark)

Q2. If 10.5 is greater than equal to 10.5 (1 mark)

Q3. If 20 is equal to 20.1 (1 mark)

Q4. If Ansh is greater than Anshu (1 mark)

Q5. If Monkey is greater than 5 (1 mark)

In [17]:
# 1
## Start code here

if (10.5>10):
    print("10.5 is greter thn 10")
else:
    print("10 is greter")

10.5>10
    

## End here

10.5 is greter thn 10


True

In [18]:
# 2
## Start code here

10.5>=10.5

## End here

True

In [19]:
# 3
## Start code here

20 == 20.1

## End here

False

In [21]:
# 4
## Start code here

'Ansh' >'Anshu'

## End here

False

In [174]:
# 5
## Start code here
'monkey'>'5'
## End here

True

## Boolean Operators

1. and
2. or
3. not

Q1. Use "and" operator to check if x is greater than 2 and less than 10. (1 mark)

Q2. Use "or" operator to check if x is grater than 3 and less than 10. (1 mark)

Q3. Use "not" operator to check if x is greater than 5 and less than 8. (1 mark)

In [44]:
# 1
## Start code here
x=10

x>2 and x < 10

## End here

False

In [45]:
# 2
## Start code here
x>3 and x<10
## End here

False

In [46]:
# 3
## Start code here
x>5 and x< 8
## End here

False

## Numpy

1. logical_and()
2. logical_or()
3. logical_not()

Q1. Use the logical_and operator to check if vol_cuboid is greater than 11 and less than 20. (1 mark)

Q2. Use the logical_or operator to check if vol_cuboid is greater than 11 and less than 20. (1 mark)

Q3. Use the logical_not operator to check if vol_cuboid is greater than 11 and less than 20. (1 mark)

In [62]:
# 1
## Start code here

np.logical_and(vol_cuboid > 11,  vol_cuboid <20)



## End here

array([ True,  True, False,  True, False])

In [63]:
# 2
## Start code here

np.logical_or(vol_cuboid > 11,  vol_cuboid <20)

## End here

array([ True,  True,  True,  True,  True])

In [64]:
# 3
## Start code here

np.logical_not(vol_cuboid > 11,  vol_cuboid <20)

## End here

array([False, False, False, False, False])

## if , elif , else

In [96]:
a = 100
b = 10

Q1. Use if condition statment to check if a is greater than b and print the greatest number. (1 mark)

Q2. Use else condition statment to check if b is greater or less than a and print the greatest number. (1 mark)

Q3. Use elif condition statment to check if b is greater , less than or equal to a and print the greatest number. (1 mark)

In [171]:
# 1
## Start code here

if a> b:
    print(a)

## End here

100


In [169]:
# 2
## Start code here



if(b>a) or (b<a):
    print(a)
    




## End here

100


In [170]:
# 3
## Start code here



if b>=a or b<a:
    print(a)

## End here

100


## Filtering pandas Dataframes

In [114]:
df = {
    "Name": ["aparna", "pankaj", "sudhir", "Geeku", "Chiku", "Jeniffer"], 
    "Degree": ["Bsc", "Engineering", "Law", "MBBS", "Phd", "Nursing"],
    "College": ["VIT", "IIT", "KIIT", "AIMS", "IIIT", "APPOLO"],
    "Score": [90, 70, 80, 98, 76, 89]} 

import pandas as pd
dataframe = pd.DataFrame(df)
dataframe

Name       Degree College  Score
0    aparna          Bsc     VIT     90
1    pankaj  Engineering     IIT     70
2    sudhir          Law    KIIT     80
3     Geeku         MBBS    AIMS     98
4     Chiku          Phd    IIIT     76
5  Jeniffer      Nursing  APPOLO     89

Q1. Access the Score column. (2 mark)

Q2. Use comparison operator to show which students has score greater than 80. (1 mark)

Q3. Use logical_and operator to see scores greater than 75 and less than 90. (1 mark)

In [123]:
# 1
## Start code here

dataframe["Score"]

## End here

0    90
1    70
2    80
3    98
4    76
5    89
Name: Score, dtype: int64

In [131]:
# 2
## Start code here

dataframe[dataframe["Score"] > 80]


## End here

Name   Degree College  Score
0    aparna      Bsc     VIT     90
3     Geeku     MBBS    AIMS     98
5  Jeniffer  Nursing  APPOLO     89

In [130]:
# 3
## Start code here
np.logical_and(dataframe[dataframe["Score"] > 75] , dataframe[dataframe["Score"] > 75] )
## End here

Name   Degree College Score
0    aparna      Bsc     VIT    90
2    sudhir      Law    KIIT    80
3     Geeku     MBBS    AIMS    98
4     Chiku      Phd    IIIT    76
5  Jeniffer  Nursing  APPOLO    89